name: UI Check CI/CD
on:
  workflow_dispatch:
jobs:
  deploy:
    name: ui check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install playwright
        run: pip install pytest-playwright pytest-json-report && playwright install

      - name: Run app
        run: docker compose up -d --build

      - name: Curl
        run: |
          sleep 5s
          curl -v http://127.0.0.1:8000/

      - name: Download UI Test File
        run: |
          curl -L "${{ secrets.CHECK_FILE }}" > ui-test.py

      - name: Run UI Tests
        run: pytest --json-report --json-report-file=./reports/ui-checker-report.json --json-report-indent=2 ui-test.py
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: ui-checker-artifact
          path: ./reports/ui-checker-report.json

      - name: Send run_id
        run: |
          sleep 30s
          curl --location 'https://api-dev.mohirpool.uz/api/site/accelerators/code-reviews/github-feedbacks/${{ github.actor }}/' \
          --header 'X-API-KEY: ${{ secrets.X_API_KEY }}' \
          --form 'action_run_id=${{ github.run_id }}' \
          --form 'project=${{ secrets.PROJECT_ID }}'
