name: UI Check CI/CD
on:
  workflow_dispatch:
  push:
    branches: [ test ]
jobs:
  deploy:
    name: ui check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install playwright
        run: pip install pytest-playwright && playwright install

      - name: Run app
        run: docker compose up -d --build

      - name: Curl
        run: |
          sleep 5s
          curl -v http://127.0.0.1:8000/

      - name: Run UI Tests
        run: pytest --json-report --json-report-file=./reports/my_report.json --json-report-indent=2 ui-test.py
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./reports/my_report.json
